### get all user
GET http://localhost:8000/user


### register new user
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "name": "r",
    "email": "aa@mail.com",
    "password": "rahasia123"
}


### login user
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "w@mail.com",
    "password": "rahasia123"
}

### request resource
GET http://localhost:8000/cookie